site_name: ZULU TMS Docs
site_url: https://docs.zuluacademy.xyz/
site_author: Zulu Academy

repo_url: https://github.com/KaiSimpson13123/zulu-docs/
repo_name: Contribute

# Copyright notice
copyright: Copyright &copy; 2025 ZULU Academy

nav:
  - Home: index.md
  - About: about.md
  - Setup Guide: setup.md
  - User Guide: user-guide.md
  - FAQ: faq.md

#Site Styling
theme:
  name: material
  logo: assets/ZULU-White.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  extra_css:
    - stylesheets/extra.css

  features:
    - navigation.instant.progress
    - navigation.footer

  font:
    text: Geist

  palette:
    scheme: slate
    primary: custom

extra:
  generator: false
