name: Docs Deploy

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml
    workflow_dispatch:
jobs:
  deploy:
    name: Docs Deploy
    runs-on: ubuntu-latest

    steps:
- name: Set Up Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://_:${{ secrets.GH_PAT }}@github.com

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build Documentation
        run: mkdocs build
        env:
          FONTAWESOME_PKG_TOKEN: ${{ secrets.FONTAWESOME_PKG_TOKEN }}

      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} ${{ github.ref_name == 'main' && '--prod' || '' }}
        working-directory: site
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
